SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A
JOIN (SELECT ANIMAL_ID, SEX_UPON_INTAKE 
 FROM ANIMAL_INS B
 WHERE SEX_UPON_INTAKE LIKE 'INTACT%') C
ON A.ANIMAL_ID = C.ANIMAL_ID
WHERE A.SEX_UPON_OUTCOME LIKE 'SPAYED%' OR A.SEX_UPON_OUTCOME LIKE 'NEUTERED%'
ORDER BY A.ANIMAL_ID