WITH users_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
),
total_users AS (
    SELECT COUNT(*) AS total
    FROM users_2021
),
purchases AS (
    SELECT
        EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
        EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
        COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM users_2021)
    GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
)
SELECT
    p.YEAR,
    p.MONTH,
    p.PURCHASED_USERS,
    ROUND(p.PURCHASED_USERS * 1.0 / t.total, 1) AS PUCHASED_RATIO
FROM purchases p
CROSS JOIN total_users t
ORDER BY p.YEAR ASC, p.MONTH ASC;