SELECT HOUR, IFNULL(COUNT, 0) AS COUNT
FROM (
    SELECT @N := @N + 1 AS HOUR FROM ANIMAL_OUTS,
    (SELECT @N := -1 FROM DUAL)NN LIMIT 24
) AS A
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HR
) AS B
ON A.HOUR = B.HR