WITH yearly_max AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    y.YEAR,
    y.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN yearly_max y ON YEAR(e.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY y.YEAR, YEAR_DEV;